// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmTloatZbw7YVOEr4fC75QvekuP7svbo0',
    appId: '1:473787085513:web:0141b8546216374d18d318',
    messagingSenderId: '473787085513',
    projectId: 'covidtracker-5bc84',
    authDomain: 'covidtracker-5bc84.firebaseapp.com',
    storageBucket: 'covidtracker-5bc84.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkG_aSFTLvT7pDKv3mNhIKgrw4-t9CHi0',
    appId: '1:473787085513:android:22854907bd64b88e18d318',
    messagingSenderId: '473787085513',
    projectId: 'covidtracker-5bc84',
    storageBucket: 'covidtracker-5bc84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6XyvnIfGlfXEUq-c4ypb_BiOVls1zGEM',
    appId: '1:473787085513:ios:74335a1d85f7a05818d318',
    messagingSenderId: '473787085513',
    projectId: 'covidtracker-5bc84',
    storageBucket: 'covidtracker-5bc84.appspot.com',
    iosBundleId: 'com.example.covidtrackerGhaziyassine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6XyvnIfGlfXEUq-c4ypb_BiOVls1zGEM',
    appId: '1:473787085513:ios:74335a1d85f7a05818d318',
    messagingSenderId: '473787085513',
    projectId: 'covidtracker-5bc84',
    storageBucket: 'covidtracker-5bc84.appspot.com',
    iosBundleId: 'com.example.covidtrackerGhaziyassine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmTloatZbw7YVOEr4fC75QvekuP7svbo0',
    appId: '1:473787085513:web:f7797a64b063321618d318',
    messagingSenderId: '473787085513',
    projectId: 'covidtracker-5bc84',
    authDomain: 'covidtracker-5bc84.firebaseapp.com',
    storageBucket: 'covidtracker-5bc84.appspot.com',
  );
}
